# Generated by Django 5.0.9 on 2024-12-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lawyer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="basedocument",
            name="contents",
            field=models.TextField(blank=True, null=True),
        ),
    ]
